extern char str_hello[];
extern char str_bitmap[];
extern char str_instructions[];
extern char str_pass[];
extern char str_fail[];
extern char str_expected[];
extern char str_got[];
extern char str_conn_check[];
extern char str_all_ones[];
extern char str_all_zeros[];
extern char str_alt_1[];
extern char str_alt_2[];
extern char str_counter[];
extern char str_picture_check[];
extern char str_checkerboard_1[];
extern char str_checkerboard_2[];
extern char str_dacs_check[];
extern char str_completed[];

extern uint8_t palette_letters[8 * 8];
extern uint8_t lut_order[8];
